### ISSUE TITLE
NameError: name 'traceback' is not defined

### ISSUE THREAD

**Issue by zszszsz** [NKUCodingCat/NKU-SSS-in-One#4]
```
        Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "prog\Launcher.py", line 100, in <module>
    traceback.print_exc()
NameError: name 'traceback' is not defined
```

**Comment by zszszsz** [comment]
在我去掉了你的try catch之后

```
        Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "prog\Launcher.py", line 98, in <module>
    choo()
  File "prog\Launcher.py", line 59, in choo
    """
  File "prog\Launcher.py", line 83, in write
    self.stream.write(data)
  File "E:\Desktop\NKU-SSS-in-One\prog\python27.zip\encodings\cp437.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3-49: character maps to <undefined>
```

**Comment by zszszsz** [comment]
while I see it is an encoding problem. Will try save it in utf-8 and see

**Comment by NKUCodingCat** [comment]
你启动的是啥啊…………

**Comment by zszszsz** [comment]
main.exe啊，嗯我是英文版系统

**Comment by NKUCodingCat** [comment]
traceback 我给改了，encoding这个坑你想填就填填完给个pr吧……这个feature我有点想砍掉来着

**Comment by NKUCodingCat** [comment]
这次你再试试

**Comment by NKUCodingCat** [comment]
中文这个你得有中文支持不然我也不会怎么办 - -

**Comment by NKUCodingCat** [comment]
https://github.com/NKUCodingCat/NKU-SSS-in-One/wiki/%E5%A6%82%E4%BD%95%E5%9C%A8%E4%B8%8D%E8%B5%84%E8%BE%9Ecp936%E7%9A%84windows%E6%8E%A7%E5%88%B6%E5%8F%B0%E4%B8%AD%E8%BF%90%E8%A1%8C%E6%9C%AC%E7%A8%8B%E5%BA%8F
